# Generated by Django 4.2.1 on 2023-06-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeimage_recipe_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='images',
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
